package com.apptogo.runner.enums;

public enum CharacterAnimationState{
	IDLE, RUNNING, JUMPING, DIEINGTOP, DIEINGBOTTOM, BORED, IDLETOMOONWALK, MOONWALKTOIDLE, LANDING, LANDINGIDLE, FLYING, BEGINSLIDING, SLIDING, STANDINGUP, FLYBOMB, RUNBOMB, FLYARROW, RUNARROW, RUNLIFT, FLYLIFT
}