package com.apptogo.runner.enums;

public enum CharacterAnimationState{
	IDLE, RUNNING, JUMPING, DIEINGTOP, DIEINGBOTTOM, BORED, LANDING, LANDINGIDLE, FLYING, BEGINSLIDING, SLIDING, STANDINGUP, FLYABILITY, RUNABILITY
}