package com.apptogo.runner.enums;

public enum ScreenType
{
	SCREEN_SPLASH,
	SCREEN_LOADING, 
	SCREEN_MAIN_MENU,
	SCREEN_CAMPAIGN,
	SCREEN_MULTIPLAYER,
	SCREEN_GAME_SINGLE,
	SCREEN_GAME_MULTI,
	SCREEN_WAITING_ROOM,
	SCREEN_NONE
}